keys:
  - &personal age159q83zjr5xyztzagq7mpt23hyn8y73cl93nyttpneelf5utt2g2scjmufz
  - &host_cassini age1nk8leddm7qeat9j0320hpn5r2rjkhprp00k7tx8yv7dda7xks9zsq9gc5n
  - &host_odyssey age1860wzxx9w4ld9jx9d6khvef7malq888qmge2gc4p2y949vlppvjqvxypaq

creation_rules:
  - path_regex: parts/secrets/[^/]+\.enc$
    key_groups:
      - age:
          - *personal
          - *host_cassini
          - *host_odyssey
  
  - path_regex: parts/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *personal          
          - *host_cassini
          - *host_odyssey
